GET http://localhost:3000/users

###
GET http://localhost:3000/users?order=oldest&limit=2&offset=2

###

GET http://localhost:3000/users/8f5fd61a-2cf7-4cf6-ad39-60329f63a27c

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5",
  "userPreference":{
    "receiveEmail": false
  }
}

###

PATCH http://localhost:3000/users/d0ced4e9-fdde-4671-b3e8-cceaee842b99
Content-Type: application/json

{
  "email": "yjkim2@example.com",
  "userPreference": {
    "receiveEmail": true
  }
}

###

DELETE http://localhost:3000/users/d3d325df-f5ed-4f28-9518-aa5f3ec8e750

###

GET http://localhost:3000/users/73cb9639-d8b7-4f11-9a62-53f4187f3f11/saved-products

###

POST http://localhost:3000/users/73cb9639-d8b7-4f11-9a62-53f4187f3f11/saved-products
Content-Type: application/json

{
  "productId": "1e112c02-7c92-4d52-b76e-485e41e3f64d"
}

###

GET http://localhost:3000/users/73cb9639-d8b7-4f11-9a62-53f4187f3f11/orders



